name: MRI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-warn-script-location flake8 pytest
          if [ -f req_production.txt ]; then pip install --no-warn-script-location -r req_production.txt; fi

      - name: Lint and Run PyTest
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build and Push Docker Image
        run: |
          docker build -t tumortrack:latest .
          docker tag tumortrack:latest jayeshgit65/tumortrack:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push jayeshgit65/tumortrack:latest

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml

      - name: Trivy File & Image Scan
        run: |
          trivy fs . > trivy_scan.txt
          trivy image jayeshgit65/tumortrack:latest > trivy_image_scan.txt
