name: MRI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-warn-script-location flake8 pytest
          if [ -f req_production.txt ]; then pip install --no-warn-script-location -r req_production.txt; fi

      - name: Lint and Run PyTest
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          pytest

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t tumortrack:latest .
          docker tag tumortrack:latest $DOCKER_USERNAME/tumortrack:latest
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_USERNAME/tumortrack:latest

      - name: Scan with Trivy (Filesystem)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml

      - name: Trivy Scan (Filesystem & Docker Image)
        run: |
          trivy fs . > trivy_scan.txt
          trivy image ${{ secrets.DOCKER_USERNAME }}/tumortrack:latest > trivy_image_scan.txt
